# Generated by Django 3.0.2 on 2020-01-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default', editable=False),
            preserve_default=False,
        ),
    ]
