# Generated by Django 3.0.2 on 2020-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_subject_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='brief_introduction',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
