# Generated by Django 3.0.2 on 2020-01-06 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_brief_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Subject'),
        ),
    ]
