# Generated by Django 3.0.2 on 2020-01-07 11:18

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subject_parent_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='parent_subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Subject'),
        ),
    ]
