# Generated by Django 3.0.2 on 2020-01-07 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200107_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replied_to',
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='children', to='blog.Comment'),
        ),
    ]
