# Generated by Django 3.0.2 on 2020-01-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200107_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_of_publish',
            field=models.DateField(auto_now_add=True),
        ),
    ]
